kind: 'CDN'
version: '1'
data:
  originSelectors:
    rules:
      - name: route-all-to-rates-injector
        when: { reqProperty: path, startsWith: "/" }
        action:
          type: selectAemOrigin
          originName: edgefunction-rates-injector
          skipCache: true
